
language: php

notifications:
  email:
    recipients:
    - kennethhendricks@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"


install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
# - moodle-plugin-ci csslint    # No CSS
  - moodle-plugin-ci shifter
# - moodle-plugin-ci jshint     # No JS
  - moodle-plugin-ci phpunit
# - moodle-plugin-ci behat      # No tests yet
