
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

dist: trusty

addons:
  postgresql: "9.4"

matrix:
  include:
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
  - export IGNORE_PATHS=classes/azure/StreamWrapper.php,classes/local/store/azure/stream_wrapper.php,classes/local/store/swift/stream_wrapper.php
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ] && [ $DB == "pgsql" ] && [[ "$MOODLE_VERSION" -gt 38 || "$MOODLE_VERSION" == "master" ]] ; then
      sudo /etc/init.d/postgresql stop;
      sudo /etc/init.d/postgresql start 9.5;
    fi
  - if [ "$MOODLE_VERSION" = "master" ] || [ "$MOODLE_VERSION" -ge 32 ]; then export CI=2; else export CI=1; fi
  - echo $CI
  - phpenv config-rm xdebug.ini
  - cd ../..
  - git clone --mirror 'https://github.com/moodlehq/moodle-behat-extension.git' '/home/travis/.composer/cache/vcs/git-github.com-moodlehq-moodle-behat-extension.git/' || true
  - if [ "$CI" = 2 ]; then
      nvm install 8.9;
      nvm use 8.9;
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
    else
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - if [ ! -z "$CORE_PATCH" ]; then (cd /home/travis/build/moodle; git apply admin/tool/objectfs/patch/$CORE_PATCH); fi

script:
  - php moodle/admin/tool/objectfs/tests/privacy/privacy.php
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
#  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker

  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci csslint    ; fi
  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci jshint     ; fi
  - if [ "$CI" -eq 1 ]; then moodle-plugin-ci shifter    ; fi

  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci savepoints ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci mustache   ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci grunt      ; fi

  - moodle-plugin-ci phpunit
# - moodle-plugin-ci behat      # No tests yet
